services:
  - type: web
    name: whatsapp-bot-universal
    env: node
    plan: free # Cambiado a free para evitar pedido de tarjeta
    region: ohio
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: LOG_LEVEL
        value: info
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: PORT
        value: 10000
