services:
  - type: web
    name: whatsapp-bot-universal
    env: node
    plan: starter # Se recomienda plan 'Starter' para evitar que el bot se 'duerma'
    region: ohio
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: LOG_LEVEL
        value: info
      - key: PORT
        value: 10000
